### ISSUE TITLE
在页面内不能正常显示

### ISSUE THREAD

**Issue by yanaex** [txperl/Moricolor-for-Typecho#1]
在编辑文章时，预览正常，在页面访问是源代码情况。
使用的是表格。
https://nishuo.me/donation.html

**Comment by yanaex** [comment]
随便说一声啊啊啊啊 好喜欢Flat UI
终于看到有Flat UI的主题

**Comment by yanaex** [comment]
表格可以正常解析了。使用的cPlayer音乐播放器插入文章在前台文章无显示。还有任何页面无法留言。。博主可以留个QQ吗QwQ

**Comment by txperl** [comment]
@nishuo  抱歉，那几天我正在上学。表格样式正常就好。cPlayer插入后不显示应该不是我主题问题，应该是插件问题。现在已经可以留言了。我会在邮箱上告诉你的。
