### ISSUE TITLE
主题不支持markdown的表格

### ISSUE THREAD

**Issue by JoyChou93** [txperl/Moricolor-for-Typecho#11]
目前typecho官方已经支持markdown表格语法，主题还不支持该表格。

类似这样：

| Status| Chrome | Firefox | Safari |
| :-: |:-: | :-: | :-: |
| test |241| 465| 500 |

**Comment by lycheeEng** [comment]
markdown表格是支持的，貌似只是不显示表格线：

![chrome_2018-04-20_11-29-24](https://user-images.githubusercontent.com/12211144/39029609-3e4640d2-448f-11e8-841c-c6eaaa719729.png)

给table添加：

`display: block;`
`width: 100%;`
`overflow: auto;`

![chrome_2018-04-20_11-34-00](https://user-images.githubusercontent.com/12211144/39029687-b4c12740-448f-11e8-8b19-d901a12fa379.png)

给td，th添加：

`padding: 6px 13px;`
`border: 1px solid #ccc;`

![chrome_2018-04-20_11-34-53](https://user-images.githubusercontent.com/12211144/39029723-e13fbde0-448f-11e8-9ef5-b63eab6b8401.png)

**Comment by txperl** [comment]
抱歉回复晚了...Typecho Markdown 解析器确实是支持表格的，但主题与解析器基本没有什么关系，至少 Moricolor 与其无关。我也测试过了，正常解析，只是因为 Flat-UI 表格样式所以你们会认为未解析。所以只要修改一下表格相关的 CSS 代码就行了。

就像 @jjhhh464 这样修改就行了，同时表示非常感谢。
蟹蟹！

**Comment by cooper1x** [comment]
主题的样式确实有问题啊，对表格的支持不友好，按照@jjhhh464的修改发现表格不能居中和占满一行呢。

**Comment by lycheeEng** [comment]
表格内容居中：table 中添加 `text-align: center;`

占满一行：把 table 中的 `display: block;` 改为 `display: table;` （不太理解你说的占满一行是什么意思

**Comment by shyandsy** [comment]
@jjhhh464 谢谢

**Comment by cooper1x** [comment]
@shyandsy 你的主页pro怎么弄的？

**Comment by shyandsy** [comment]
@cooper1x 什么pro？

**Comment by cooper1x** [comment]
@shyandsy 
![image](https://user-images.githubusercontent.com/9080789/53214591-19558d00-3688-11e9-8402-ee16d6f7bf3a.png)

**Comment by shyandsy** [comment]
@cooper1x 
我说我不知道你信么。。。
但是在你问我之前我都没注意到我这里有个pro。。。

**Comment by txperl** [comment]
@cooper1x 那是 GitHub Pro 用户的标示，类似会员。
`https://github.com/settings/billing`  可以在这查看自己的用户类型。
他不知道自己为什么会有 Pro，多半申请了 GitHub 教育优惠，貌似会自动开通 Pro 两年？

**Comment by shyandsy** [comment]
@txperl 貌似是这样

还给我了个coupon

Coupon
You have an active coupon for $7.00 off for 2 years, until 2020-11-15.
