### ISSUE TITLE
Flat-UI CSS加载好慢哦

### ISSUE THREAD

**Issue by LamiaLoveless** [txperl/Moricolor-for-Typecho#12]
css文件大,而且CF国内访问也有很大问题

**Comment by txperl** [comment]
那之后更新换成国内CDN吧...

**Comment by txperl** [comment]
已经在最新的 [v1.4](https://github.com/txperl/Moricolor-for-Typecho/releases/tag/a7c4107) 版本中更换了 CDN 了。
