### ISSUE TITLE
wordpress有可能用上吗？

### ISSUE THREAD

**Issue by potoo0** [txperl/Moricolor-for-Typecho#16]
好喜欢这个主题啊。前端小白的我用了很久 wordpress，wp有用这个主题的办法吗？T_T

**Comment by txperl** [comment]
有，只要移植适配过去就行了。有打算移植到 WordPress ，但不知道什么时候会去做...

**Comment by potoo0** [comment]
好期待(๑˙ー˙๑)。你什么时候移植适配下吧，大大，我同学也很喜欢，我们都非常期待。
