### ISSUE TITLE
请教关于文章展示页面的TODO目录功能

### ISSUE THREAD

**Issue by hi-KK** [txperl/Moricolor-for-Typecho#17]
请问怎么能把文章展示页面的TODO目录功能默认显示出来
而不是需要在页面点击一下才显示
还有一个问题
怎么能把TODO显示调大一点点，默认的有点小，希望能支持三级目录，目前的我看是h3-h4 两级
还望解答，谢谢

**Comment by txperl** [comment]
你指的是导航树吧...主题不支持默认显示导航树。

不过你可以在 `footer.php` 的 `$(document).ready(function(){ });` 中加入

```
$("#postTor").fadeIn(400);
$("#postTor").css('display','inline-block');
```

使其默认加载。

---
调大的话，可以自行修改 CSS 代码即可。这我就不说了，自行简单学习一下即可。

---
要支持三级目录的话，可以自己更改 `functions.php` 中导航树解析与输出的相关代码。

**Comment by hi-KK** [comment]
谢谢解答，我已经根据你说的方法实现功能了  : D
