### ISSUE TITLE
请问下MoriGarden[Beta]默认的api是失效了吗

### ISSUE THREAD

**Issue by narakuzi** [txperl/Moricolor-for-Typecho#18]
你好,我在开启`beta_MoriGarden`后,编辑 `./MoriGarden/config.php `文件后保存还是无法正常显示,请问是api失效了吗

**Comment by txperl** [comment]
我这边没有问题。有演示地址吗？

**Comment by narakuzi** [comment]
> 我这边没有问题。有演示地址吗？

https://naraku.xyz

**Comment by txperl** [comment]
emm 你不是关了...那你 `config.php` 里的配置项是怎么填的？

**Comment by narakuzi** [comment]
> emm 你不是关了...那你 `config.php` 里的配置项是怎么填的？

因为没生效我就关了…

**Comment by narakuzi** [comment]
> emm 你不是关了...那你 `config.php` 里的配置项是怎么填的？
<br>
我配置是这样的

>$GLOBALS['api_url'] = 'https://api.tls.moe/'; 
$GLOBALS['twitter'] = 'ealisalily';

**Comment by txperl** [comment]
API 和主题代码都没问题。应该是你的自己（插件）添加的 JS 问题，具体请自行 Debug。
