### ISSUE TITLE
markdown语法增强

### ISSUE THREAD

**Issue by xunhs** [txperl/Moricolor-for-Typecho#20]
哈喽博主，你的主题非常好看，我已经用了接近两个月啦，非常感谢哈～
有一个问题想请教一下，我是用的markdown编辑器，内置的markdown（开发版）不支持`TOC`等一些语法，还有添加公式。使用其他markdown插件后function.php等函数失效，我想请教一下博主能否在主题中强化一下对markdown语法的支持呢？包括公式等功能（科研狗需要:<）
第二个事情想反馈一下，index页面的搜索功能，只能搜索标题中的字符，不能搜索标签和内容中的字符。请问博主是否可以改进一下呢？
再次非常感谢博主的主题，真的太喜欢了～～

**Comment by txperl** [comment]
请问“其他 markdown 插件”指的是？`function.php` 是指 Moricolor 的吗？

这个之后更新可能会加入的。
