### ISSUE TITLE
似乎主页的分页按钮操作有点奇怪

### ISSUE THREAD

**Issue by xcz1997** [txperl/Moricolor-for-Typecho#4]
虽然讲得通，但是对于大部分用户似乎下意识next按钮是下一页，即点击next按钮显示剩余部分，而不是点击previous按钮显示。所以可否添加一条config设置一下？

**Comment by txperl** [comment]
确实唉，代码已修改。感谢反馈。

**Comment by JoyChou93** [comment]
我刚clone的最新的代码，还是有这样的问题…
