### ISSUE TITLE
你好开发者，一直用这个主题，非常漂亮，有两个问题请教！

### ISSUE THREAD

**Issue by zhenyangleo** [txperl/Moricolor-for-Typecho#6]
新手，小白，做个网站谢谢东西发发信息。一直用你的这个主题，非常漂亮。

对主题代码不是非常熟悉，根据自己的要求简化了下。我的博客 www.yang-zhen.cn

有两个问题想要请教下！

1. 文章页面的标题无论在电脑浏览器还是在手机端，都有点太大了。这个是否可以通过相关代码调整下字体大小？
2. 有些页面如果插入视频的话，在电脑上显示没有问题，比如：[优酷视频外链](http://www.yang-zhen.cn/2017/03/02/hans-zimmer-inception.html)，但是在手机上显示的话，排版就不是很好看了。
如果把视频的大小调小一点，我试过调整到250*300，手机上显示OK，但是这样电脑上显示也非常小，不好看。
这个可以调整吗？让手机和电脑上显示不同大小，自行适应。

不好意思，我是小白一个，期待你的解答。当然，如果你有时间的话！感谢！

**Comment by txperl** [comment]
很感谢你能喜欢。建议可以去学习一下CSS，这样你的两个问题或者更多问题就可以解决了。也不需要太深入，解决你的问题只需入门就行了。以下回答你的问题...

1.当然可以调整的。如果你只想调整标题大小，最有针对性的方法就是：将 post.php第7行 修改为 `<h2 style="font-weight: normal;font-size: 30px;"><?php $this->title() ?></h2>` 即可。字体大小就是
 30px。

2.这是你引用的播放器自适应问题。将引用代码中width值改为100%，这样 `width="100%"` 即可。

**Comment by zhenyangleo** [comment]
嗯嗯，谢谢你的回复！！
本来是想自己建个小站写写东西，发发通知，没想到让网站按照自己意愿展示出来还是有些小问题的。
有机会一定去学习下！
再次感谢！

**Comment by zhenyangleo** [comment]
非常感谢！之前提出的两个问题都基本解决了。标题调整立竿见影啊！引用视频链接自适应貌似还没有简单我能理解的解决办法，但是用你的方法也基本解决了：[优酷视频链接](http://www.yang-zhen.cn/2017/11/29/hans-time-reynah.html)。手机端高度有点高但是基本可以接受！

非常不好意思，还有个问题，因为之前一直没有用过正文标题功能，今天使用的时候发现以下问题：

1. 如图：
![2017-12-03 21 21 56](https://user-images.githubusercontent.com/25653836/33525709-2a7bb6da-d870-11e7-8f4f-da69d2c6a074.png)
![2017-12-03 21 23 52](https://user-images.githubusercontent.com/25653836/33525717-4d95518a-d870-11e7-8583-7e27b952da1a.png)
后台编辑器输入后，显示出来的标题h4显示这样是特意做成这样的吗？

2. 之前以因为调整了post页面主标题的大小，如果我想要调整下正文中不同层级标题的大小，是要通过CSS吗？应该在哪个里面进行相应的调整？

因为没有基础，我尝试找遍了
`flat-ui.min.css`
`bootstrap.min.css`
`flat-ui.css`
也没搞清楚在哪里去调整大小。

尝试修改了以下数据，然并卵！
![2017-12-03 21 31 40](https://user-images.githubusercontent.com/25653836/33525784-70c660b2-d871-11e7-80b1-3fffcbc4a4ec.png)

很抱歉打扰了。

**Comment by txperl** [comment]
1.是的，是我自定义的。

2.各h标签大小好像是在 mori.css 中更改。还有，你代码貌似写错了…

**Comment by zhenyangleo** [comment]
好的，谢谢，明天试试看！
👍 👍

**Comment by zhenyangleo** [comment]
按照你的提示，自己修改了CSS，完美解决！谢谢！
