### ISSUE TITLE
请问有没有支持pjax的打算？

### ISSUE THREAD

**Issue by AlanDecode** [txperl/Moricolor-for-Typecho#7]
开发者你好，主题非常漂亮，很喜欢呢

请问后续开发会不会考虑支持pjax？对网页浏览体验提升应该还蛮大的

**Comment by txperl** [comment]
@AlanDecode 
感谢你能喜欢。
其实我很早之前就想加入PJAX了，因为这样不仅切换体验好，页面加载动画也可以更流畅显示。但貌似很多带有PJAX的Typecho主题时不时会出现莫名其妙的BUG，比如说不能评论什么的…所以到现在我还没有写。不过日后可能会写一个版本尝试一下。

**Comment by AlanDecode** [comment]
@txperl 
明白了～期待
