### ISSUE TITLE
能否自定义快速预览

### ISSUE THREAD

**Issue by sulf1ron** [txperl/Moricolor-for-Typecho#8]
对于有结构的文章，快速预览会包含结构性的文字。
以这个站点为例：https://imjad.cn/ 非常混乱

> 首先，一首届不到的恋送给大家： 前言 又到了白色相簿的季节，给博客加上雪花效果是再好不过的了。 两年前差不多这个时候我介绍过一个插件，可以实现雪花效果。但那个插件基于3JS和jQuery，且CPU消耗过大。 经过寻找后，我找到了一个较为满意的版本Demo，并将其做成了插件形式。 相比两年前的版本，这次的插件有如下特点:

所以可以加入自定义快速预览内容的功能吗，谢谢！

**Comment by txperl** [comment]
就是需要自已输入快速预览内容吗？

**Comment by sulf1ron** [comment]
是的

**Comment by txperl** [comment]
已在最新版本 [v1.2!](https://github.com/txperl/Moricolor-for-Typecho/releases/tag/bbe84d8) 中增加此功能

---
 - 自定义快速预览内容

在文章中加入 `<!-- des_quick:your_words; -->` ，将 your_words 改成你需要的内容即可。

---
感谢反馈
