### ISSUE TITLE
对markdown checkbox的支持

### ISSUE THREAD

**Issue by chinobing** [txperl/Moricolor-for-Typecho#9]
为啥markdown中的checkbox显示不了？我已经加入了“MarkdownParse”的插件，正常来说可以显示最新的markdown语法。

**Comment by txperl** [comment]
请先判定确实是 Moricolor 主题引起的，要不然我也不知道是不是主题的BUG。如果不是，那就凭你这句话我是不可能知道为什么的...
Markdown 语法解析是用 Typecho 原生函数，没有做任何更改。
